Import('env')
import datetime
import os

now = datetime.datetime.now()
version = now.strftime("%y%m%d")
date_str = now.strftime("%Y-%m-%d %H:%M:%S")

header = '''#pragma once
// Auto-generated by scripts/generate-build-info.py
// Do not edit manually

#define BUILD_VERSION "{}"
#define BUILD_DATE "{}"
'''.format(version, date_str)

build_info_path = os.path.join(env['PROJECT_DIR'], 'include', 'BuildInfo.h')
with open(build_info_path, 'w') as f:
    f.write(header)

print("BuildInfo: version={}, date={}".format(version, date_str))
