Import('env')
import datetime
import os

# 使用北京时间（Asia/Shanghai），避免 CI 服务器 UTC 时差问题
now = datetime.datetime.now(datetime.timezone.utc).astimezone(datetime.timezone(datetime.timedelta(hours=8)))
version = now.strftime("%y%m%d")
date_str = now.strftime("%Y-%m-%d %H:%M:%S")

header = '''#pragma once
// Auto-generated by scripts/generate-build-info.py
// Do not edit manually

#define BUILD_VERSION "{}"
#define BUILD_DATE "{}"
'''.format(version, date_str)

build_info_path = os.path.join(env['PROJECT_DIR'], 'include', 'BuildInfo.h')
with open(build_info_path, 'w') as f:
    f.write(header)

print("BuildInfo: version={}, date={}".format(version, date_str))
